# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Validate

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate Using Node 16
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.0-chrome99-ff97
      options: --user 1001
    steps:
      - uses: actions/checkout@v3

      - name: Run Lint and Typecheck
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - run: yarn
      - run: yarn lint
      - run: yarn typecheck

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          browser: chrome

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
